server {
    listen 80;
    server_name books.zabeyda.lol;

    root /root/books/webapp;
    index index.html;

    location /reads {
        proxy_pass http://127.0.0.1:5000/reads;
        proxy_set_header Host $host;
    }

    location /read/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(png|jpg|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location ~* \.(json|js|css|html)$ {
        expires -1;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
    }
}
